structure          wat_graphene_nacl.psf
coordinates        wat_graphene_nacl.pdb

set temperature    300.0
set outputname     wat_graphene_nacl_prod
set length	   10000000

set inputname      wat_graphene_nacl_eq_NPT
binCoordinates     $inputname.restart.coor
binVelocities      $inputname.restart.vel
extendedSystem     $inputname.restart.xsc

paraTypeCharmm		on
parameters              toppar/par_all36m_prot.prm
parameters              toppar/par_all36_na.prm
parameters              toppar/par_all36_carb.prm
parameters              toppar/par_all36_lipid.prm
parameters              toppar/par_all36_cgenff_modified_for_mecn.prm
parameters              toppar/toppar_all36_moreions.str
parameters              toppar/toppar_water_ions.str
parameters              toppar/toppar_ions_won.str

exclude			scaled1-4
1-4scaling		1.0
switching		on
vdwForceSwitching	on
cutoff			12.0
switchdist		10.0
pairlistdist		14.0
stepspercycle		20

timestep		2.0  
rigidBonds		all
#useSettle		on
nonbondedFreq		1
fullElectFrequency	1

wrapWater		on
wrapAll			on
wrapNearest             off

PME                     yes
PMEInterpOrder          6
PMEGridSpacing          1.0

langevin            on
langevinDamping     1
langevinTemp        $temperature
langevinHydrogen    off	

useGroupPressure       yes	
useFlexibleCell        no
useConstantRatio       no
langevinPiston        on
langevinPistonTarget  1.01325
langevinPistonPeriod  50.0
langevinPistonDecay   25.0
langevinPistonTemp    $temperature

outputName          $outputname
restartfreq         50000
dcdfreq             50000
dcdUnitCell         yes
xstFreq             5000
outputEnergies      5000
outputPressure      5000

fixedAtoms          on
fixedAtomsFile      constraint.ref
fixedAtomsCol       O

run 			$length